disp("Welcome to Get to Know You!")
disp("In this game, we will ask you 10 questions to make you think more")
disp("about yourself and to let us get to know you!")
disp("You can answer in either French, Spanish, or English.")
disp("After each question, we will let you know what language you")
disp("answered in and we will adjust accordingly!")
disp(" ")
disp("Here are some rules:")
disp("1. Please answer the question as straightforwardly as possible")
disp("2. Please adhere to the grammar rules of the language! Start with capital letters, etc.") 
disp("3. Please answer in full sentences, such as 'My favorite song is...'")
disp("4. Be careful with typos, incorrect grammar, etc. as it may not detect your language!")
disp("5. Have fun and learn more about yourself along the way!")
disp(" ")

gtky()